apiVersion: v1
kind: Service
metadata:
  name: gtd-deep-analysis-worker
  labels:
    app: gtd-deep-analysis-worker
spec:
  selector:
    app: gtd-deep-analysis-worker
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP

